# https://hub.docker.com/r/fluent/fluent-bit
# https://hub.docker.com/r/fluent/fluent-bit/tags
# https://docs.fluentbit.io/manual/local-testing/logging-pipeline
services:
  fluent-bit:
    image: fluent/fluent-bit:3.2.6
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - ./test.log:/fluent-bit/etc/test.log
